services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Qc\QcComments\:
    resource: '../Classes/*'

  Qc\QcComments\Domain\Repository\CommentRepository:
    public: true




