services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Qc\QcComments\:
    resource: '../Classes/*'

  Qc\QcComments\Domain\Repository\CommentRepository:
    public: true

  Qc\QcComments\Controller\CommentsBEController:
    tags: [ 'backend.controller' ]

  Qc\QcComments\Controller\StatisticsBEController:
    tags: [ 'backend.controller' ]




